### ISSUE TITLE
Implement delay object and macro

### ISSUE THREAD

**Issue by jeaye** [jank-lang/jank#118]
This will follow Clojure's delay (`Delay.java`). Community docs: https://clojuredocs.org/clojure.core/delay

We already have support for `@` and `deref`, but `force` and `delay` don't exist yet.

1. Create a new `object_type` for `delay` (under `reduced`)
2. Add a case for `delay` under `reduced` in `visit_object`
3. Copy `volatile.hpp` into `delay.hpp` and implement `deref`
4. Add `delay` and `force` to clojure.core

**Comment by jianlingzhong** [comment]
will take this one.

**Comment by jianlingzhong** [comment]
https://github.com/jank-lang/jank/pull/123 should have completed this feature.

**Comment by jeaye** [comment]
Yep. In the PR, you can add "This closes #nnn" and Github will do it for us automatically.
