### ISSUE TITLE
Question: Memory management model in `native/raw`

### ISSUE THREAD

**Issue by funatsufumiya** [jank-lang/jank#130]
Hello. I'd like to know the memory management within C/C++ interop.

I'm glad If there is same kind of document like C-API of Janet lang.
- https://janet-lang.org/capi/index.html
- https://janet-lang.org/capi/memory-model.html

This document explains custom memory management using Janet GC.

In this context, I'd like to know what considerations should be made regarding GC when doing C/C++ interop with jank-lang.

**Comment by jeaye** [comment]
Hi! Thanks for the interest in jank.

jank is garbage collected and any objects flowing through the jank system must be boxed in a jank object. The special `native/raw` form has been removed, along with jank now generating LLVM IR, but jank can still load and JIT compile C++ so the question still applies. In C++ code, normal C++ ownership rules apply. For anything interacting with the jank world, jank provides an API for boxing values to ensure they'll live as long as needed and be collected when not needed. This doesn't impact any non-jank code.

We'll definitely have docs for this, as part of jank's production release. For now, jank is very much pre-alpha and under heavy development. Hang in there while we get jank ready for prime time!

**Comment by funatsufumiya** [comment]
Thank you for your detailed explanation. I understood it very well.
