### ISSUE TITLE
Create native_pointer_wrapper

### ISSUE THREAD

**Issue by jeaye** [jank-lang/jank#136]
jank needs a way to store arbitrary native pointers as boxed objects. Until we get to a point where the jank compile/runtime can understand and codegen arbitrary C or C++ types, hiding things behind an opaque pointer will be necessary.

native_pointer_wrapper will store a `void*`. We should be able to construct it with a `void*` and then pull the pointer out as some other type. We don't need any jank fns for this. This will be used for storing arbitrary native pointers in a jank object. When you pull it out, you can cast it to the type you want and it's up to you to make sure it's correct.

```cpp
auto box{ make_box<obj::native_pointer_wrapper>(my_database_obj) };

// later on
void foo(object_ptr const o)
{
  auto box{ try_object<obj::native_pointer_wrapper>(o) };
  database *db{ box->as<database>() };
}
```

**Comment by Samy-33** [comment]
On it.
