### ISSUE TITLE
failed to build on guix

### ISSUE THREAD

**Issue by faust45** [jank-lang/jank#18]
Hi!
i am trying to build jank on guix
just run bin/configure and got this

-- Running vcpkg install
-- Running vcpkg install - failed
CMake Error at third-party/vcpkg/scripts/buildsystems/vcpkg.cmake:863 (message):
  vcpkg install failed.  See logs for more information:
  /home/moon/code/jank/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /gnu/store/5p4fnymnslnydibk7qcisal3443w09pm-cmake-minimal-3.21.4/share/cmake-3.21/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:17 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

jank/build/vcpkg-manifest-install.log
is empty

Thanks!

**Comment by jeaye** [comment]
Hi! Thanks for your interest in jank. I followed up in Slack, asking if you'd mind sharing more info. This would help:

1. The values of `CXX` and `CC` in your shell
2. The exact commands you're running to configure and build jank
3. The contents of the `vcpkg-manifest-install.log` referenced in that error output

Thanks!

**Comment by jeaye** [comment]
Happy new year! Closing this, since I haven't heard back in a while. Note that jank isn't production ready yet, or even usable yet, so compiling it right now is left for the adventurous and the curious. If you do get this compiling on Guix, please do share your approach so we can make it easier for others!
