### ISSUE TITLE
failed to build on arch linux

### ISSUE THREAD

**Issue by glyh** [jank-lang/jank#20]
Log here:
https://pastebin.ubuntu.com/p/7GmBgxCyn2/

**Comment by glyh** [comment]
Why do I have to build cling? Can't I use some prebuilt binaries?

**Comment by jeaye** [comment]
Hey! Thanks for your interest. For now, jank is not yet production ready. From the readme:

> For the current progress of jank and its usability, see the tables here: https://jank-lang.org/progress/
> 
> The current tl;dr for jank's usability is: getting there, but not ready for use yet.

Part of that readiness would entail prebuilt binaries. If you're trying to work on jank, you'll need to build it yourself, including Cling, though we may end up with prebuilt binaries for Cling to aid in development going forward. That's a low priority compared to implementing language features. :)

My recommendation for now, if you don't want to debug what's going on, is to hold off until jank is more complete. However, if you are going to dig deeper, note that I'm developing jank on Arch Linux, so I'd expect it's just some missing packages or incorrect environment variables which caused this.
