### ISSUE TITLE
Update vcpkg to have the latest immer

### ISSUE THREAD

**Issue by jeaye** [jank-lang/jank#27]
We use immer for persistent, immutable data structures in C++ and we use vcpkg to fetch our C++ packages at build time. Unfortunately, the latest vcpkg version for immer doesn't have some new features he's released, like map transients. Updating this would allow us to use those.

**Comment by seanstrom** [comment]
Recently we've updated the vcpkg submodule and now the vcpkg-port version for Immer is 0.8.0
Is the version of Immer that we're trying to use?

**Comment by jeaye** [comment]
Ah, yes. We do have the latest immer now, so this can be closed. I'll open another one to take advantage of using immer's map transients.

Thanks!
