### ISSUE TITLE
Build failed on Arch Linux

### ISSUE THREAD

**Issue by glyh** [jank-lang/jank#35]
Here's what I got:
```
/home/lyh/Documents/CS/jank/jank/build/llvm/include/llvm/Support/Signals.h:119:24: error: unknown type name 'uintptr_t'; did you mean '__intptr_t'?
/home/lyh/Documents/CS/jank/jank/build/llvm/lib/Support/Unix/Signals.inc:348:11: error: out-of-line definition of 'CleanupOnSignal' does not match any declaration in namespace 'llvm::sys'
```

**Comment by jeaye** [comment]
Building LLVM, Cling, and Clang is a real pain. They fail in all sorts of different ways. I'm looking to tackle this using #26. For now, jank is not very usable (as I try to convey in the README). Do you mind if I close this as a result of #26 not being done?
