### ISSUE TITLE
In Readme.md : change =cling-build to =build/cling-build ?

### ISSUE THREAD

**Issue by kloimhardt** [jank-lang/jank#39]
I followed the compiling instructions and got a "hello world" working on my Mac! Hurray!

One thing: I had to type
```
./bin/configure -Djank_cling_build_dir=build/cling-build
```
I needed three attempts to figure this out, the info in the Readme led me to  
plain `./bin/configure` and then `./bin/configure -Djank_cling_build_dir=cling-build`.

Maybe it makes sense to clarify this in the Readme for Clojurians (like me) who  in the last decade had used `make` and `C++` maybe once and now building Jank with "fingers crossed".

**Comment by jeaye** [comment]
Ah, I can see how the list of scripts was misleading you. I'll clarify that and fix the build dir path, as per your suggestion. **Thanks for pushing through it and taking the time to leave feedback!** Will close this with the commit, once it comes through. I'm in the middle of some big changes right now, but I'll get this closed this weekend.
