### ISSUE TITLE
Add ratio support

### ISSUE THREAD

**Issue by jeaye** [jank-lang/jank#66]
Clojure supports `3/4` as a ratio. ClojureScript supports this at the reader level, but not at the object level. It will just read it as `(/ 3.0 4)`, whereas Clojure has a specific ratio object.

For jank, let's follow ClojureScript here until we have a reason to add a ratio object.

Official docs on this: https://clojure.org/reference/data_structures#_ratio

**Comment by jianlingzhong** [comment]
sent a pr for this https://github.com/jank-lang/jank/pull/117.

**Comment by jeaye** [comment]
Keeping this open, since we have limited support for ratios now. We lex them and parse them into a real, but we don't yet have a lossless ratio object.
