### ISSUE TITLE
Can Jank interop with Swift via C++?

### ISSUE THREAD

**Issue by filipesilva** [jank-lang/jank#77]
Swift seems to have decent [C++ interop](https://www.swift.org/documentation/cxx-interop/#accessing-swift-apis-from-c). Would it be plausible to use Jank's C++ interop to do iOS and Mac apps in Jank?

**Comment by jeaye** [comment]
Hey Filipe! In general, if you can do it in C++, you can do it in jank. jank currently allows you to compile C++ sources alongside your jank sources and then require those C++ files as namespaces from your jank code. So I certainly think this will be possible.

However, worth noting that [Apple is strict about JIT compilation](https://stackoverflow.com/questions/5054732/is-it-prohibited-using-of-jitjust-in-time-compiled-code-in-ios-app-for-appstor). When you ship, you'd need to do so with fully AOT compiled builds with a static runtime (i.e. no `eval`, no REPL support, no JIT compilation). During development, though, you should, in theory, be able to REPL right from your editor into your phone and develop interactively. :grin: 

All of this is dependent on jank releasing. Right now, it's not yet ready to be used for this sort of thing.

**Comment by filipesilva** [comment]
Got it, thanks for taking the time to reply!
