### ISSUE TITLE
Add CLI REPL history persistence

### ISSUE THREAD

**Issue by jeaye** [jank-lang/jank#85]
We're using readline for the jank and native CLI REPLs. This gives us history within a session, but persisting that would be super helpful for iteration. Since we have two CLI REPLs, we should have two history files.

From what I can tell, the correct docs are here: https://tiswww.case.edu/php/chet/readline/history.html

If there's a more modern library for this, I'm open to us using that instead.

-----

EDIT: LLVM has a `LineEditor` which uses libedit (Editline) behind the scenes. Example usage is here: https://github.com/llvm/llvm-project/blob/main/clang/tools/clang-repl/ClangRepl.cpp#L228-L232

If this works, we should stick with it. Otherwise, we can consider: https://github.com/antirez/linenoise

**Comment by neoeleatic** [comment]
I hate to be this guy, but it appears to me that maybe you can't use GNU readline in Jank? It is GPL and in Jank's license file you state it's MPL2 and incompatible with secondary licenses. The MPL FAQ (https://www.mozilla.org/en-US/MPL/2.0/FAQ/) states in Q14 that you can't combine code in this case.

I might very well be wrong since I'm thankfully not a license expert. It's just something I noticed while browsing issues. 

Some people like to use Editline (https://www.thrysoee.dk/editline/) as an alternative.

**Comment by raoulmillais** [comment]
The MPL v2 is GPL compatible provided the software is dual-licensed. https://www.mozilla.org/en-US/MPL/2.0/FAQ/#mpl-and-lgpl

**Comment by jeaye** [comment]
> I hate to be this guy, but it appears to me that there might be a licensing issue when using GNU readline in Jank. readline is GPL and in Jank's license file you state it's MPL2 and incompatible with secondary licenses. The MPL FAQ (https://www.mozilla.org/en-US/MPL/2.0/FAQ/) states in Q14 that you can't combine code in this case.
> 
> I might very well be wrong since I'm thankfully not a license expert. It's just something I noticed while browsing issues.
> 
> Some people like to use Editline (https://www.thrysoee.dk/editline/) as an alternative.

Super cool of you to call this out! Nothing to hate. Rather than changing any licensing, we can replace readline for a more flexibly licensed alternative. Thanks, also, for pointing out Editline.

I believe that LLVM has line editing functionality and we're already embedding it, so I think it makes sense to move in that direction first.

**Comment by neoeleatic** [comment]
Cool, I didn't know about LLVM's LineEditor at all, so I had to check it out. As it turns out, it also uses Editline under the hood. Look at https://github.com/llvm/llvm-project/blob/1701895c362176cb898eba509b18e8d72d8095c9/llvm/lib/LineEditor/LineEditor.cpp#L92, LIBEDIT is Editline.

**Comment by ValorZard** [comment]
@jeaye what do you mean by two CLIs and two history files? all i see is the jank CLI

**Comment by jeaye** [comment]
We have a cpp-repl command and a repl command. The former takes in C++ code, the later takes in jank code. We can actually skip the cpp-repl command now and just do the repl command.

**Comment by jeaye** [comment]
This is closed by #125. We now use libedit, as wrapped by LLVM.
