### ISSUE TITLE
Support all simple string escape sequences

### ISSUE THREAD

**Issue by jeaye** [jank-lang/jank#97]
Currently, we support only `\n` and `\t` properly. We have partial support for `\r`, too. Let's support all of the simple escape sequences listed here:  https://en.cppreference.com/w/cpp/language/escape

- [ ] Add lexing support for each escape sequence (in lex.cpp)
- [ ] Add escape/unescape support for each escape sequence (in escape.hpp/cpp)
- [ ] Update the lexing tests to include all supported sequences
- [ ] Update the parse tests to include all supported sequences

**Comment by jianlingzhong** [comment]
started with a simple pr first: https://github.com/jank-lang/jank/pull/101
